services:
  electrs:
    image: mempool/electrs:v3.2.0
    container_name: electrs
    restart: unless-stopped
    network_mode: host
    command:
      - -vvvv
      - --network=mainnet
      - --db-dir=/data/db
      - --daemon-rpc-addr=127.0.0.1:8334
      - --cookie=user:pass
      - --jsonrpc-import
      - --http-addr=0.0.0.0:3002
      - --daemon-dir=/bitcoin
      - --electrum-rpc-addr=0.0.0.0:50001
    volumes:
      - /root/electrs/data:/data
      - /root/myfork:/bitcoin:ro

  nginx:
    # SilverRuler님의 커스텀 이미지
    image: silverruler/bitever-esplora-frontend:v1.1
    container_name: bitever-esplora-nginx
    restart: unless-stopped
    network_mode: host
    volumes:
      - /root/bitever-esplora/nginx/esplora-nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # --- 파비콘 덮어쓰기 설정 (HTML 소스에서 지정한 경로 포함) ---
      - ./bitever-favicon.png:/usr/share/nginx/html/favicon.ico:ro
      - ./bitever-favicon.png:/usr/share/nginx/html/favicon.png:ro
      - ./bitever-favicon.svg:/usr/share/nginx/html/favicon.svg:ro
      - ./bitever-favicon.png:/usr/share/nginx/html/img/favicon.png:ro
      # -------------------------------------------------------

  haproxy:
    image: haproxy:lts-alpine
    container_name: bitever-esplora-haproxy
    restart: unless-stopped
    network_mode: host
    volumes:
      - /root/bitever-esplora/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - /root/bitever-esplora/haproxy/certs:/etc/haproxy/certs:ro
